---
title: "Getting started"
subtitle: ""
description:  |
  Directions to set up your website and create your first post.
author: "Daniel Sussman"
date: "2024-02-23"
# image: ""
image-alt: ""
categories: []
date-modified: "2024-02-23"
draft: false
---

Below, the items marked with **[[OP]]** should only be done by one person on the team.

### To get started

1. **[[OP]]** One person from the team should click the Github Classroom link on Teams.
2. **[[OP]]** That person types in the group name for their group.
3. The rest of the team now clicks the Github Classroom link and selects their team from the dropdown list.
4. Finally, each of you can clone the repository to your laptop like a normal assignment.

### Setting up the site

1. **[[OP]]** Open the terminal and run `quarto publish gh-pages`.
2. **[[OP]]** Select `Yes` to the prompt: <br> `? Publish site to https://sussmanbu.github.io/ma4615-fa23-final-project-TEAMNAME/ using gh-pages? (Y/n)`
3. **[[OP]]** Wait for the process to finish.
4. Once it is done, you can go to the URL it asked you about to see your site.

**Note**: This is the process you will use every time you want to update your published site. Make sure to always follow the steps below for rendering, previewing, and committing your changes before doing these publish steps. Anyone can publish in the future.

### Customize your site

1.  **[[OP]]** Open the `_quarto.yml` file and update the title to include your team name.
2.  **[[OP]]** Go to the `about.qmd` and remove the TF's and professor's names.
3. add your own along with a short introduction and a link to your Github user page.
4.  **[[OP]]** Render the site.
5.  **[[OP]]** Check and make sure you didn't get any errors.
6.  **[[OP]]** Commit your changes and push.
7.  **[[OP]]** Repeat the steps under Setting up your site.

Once one person is done with this, each teammate in the group can, in turn, repeat steps 3-7. Before doing so, make sure to `pull` the changes from teammates before starting to make new changes. 
(We'll talk soon about ways to organize your work and resolve conflicts.)

### Start your first post

1. To start your first post first, run `remotes::install_github("sussmanbu/quartopost")` in your Console.
2. **[[OP]]** Run `quartopost::quartopost()` (or click Addins->Create Quarto Post, or use C-Shift-P, type "Create Quarto" and press enter to run the command).

Now you can start working on your post.
You'll want to render your post to see what it will look like on the site.

* Every time you want to **make a new post**, you can repeat step 2 above.
* When you want to **publish your progress**, follow steps 4-7 from Customize your site.

Finally, make sure to read through everything on [this site](https://sussmanbu.github.io/ma4615-final-project-quarto) which has the directions and rubric for the final project.

