 ---
title: "Blog Posts 3 - Data Cleaning, Loading, and Equity Considerations"
subtitle: ""
author: "Group 1"
date: "2024-10-28"
date-modified: "2024-10-28"
draft: false
---

## Data Cleaning
 
In our recent data cleaning work, we started by removing columns that had a high percentage of missing values, specifically those with over 80% missing data, to ensure the reliability of our analysis. We then transformed the format of columns "Local Case Number" to a character format to preserve specific formatting details, and the "Crash Date and Time" to a datetime format for better temporal analysis.

Additionally, we addressed missing entries in the "Route Type" column by filling them with the most frequently occurring value, ensuring consistency in our categorical data. We also removed all duplicate entries to maintain the uniqueness of the dataset.

## Data Equity

We can utilize the principles for advancing equitable data practices by applying the principles of beneficence, respect for persons, and justice to the exploration of our data set. 

These principles are relevant for a few reasons. First, looking at beneficence, we may consider how the findings in our data set are being used by local or federal governments, as well as how we are using the data. We can see from this principle what the best actions for the county to take in response to traffic violations would be. Additionally adhering to this practice for our group's project may look like researching into how the government is using this dataset. 

Furthermore, we can look at the principle of justice. This is relevant to our data as we can see the members of this sample that are facing violations or get into accidents. We can see if they are more at risk than others, and provide some insight through our findings to see if there is any injustice within this county of Maryland response, whether through law or bill. 

Some limitations of our analysis could include missing data, variables not provided or included in the dataset, and a lack of available information online to evaluate the local or federal government's response (or lack thereof) to this data. Potential misuse of the data could involve government surveillance in high-risk areas or the implementation of strict law enforcement measures. It could also manifest as policy changes made without community input, which might, in turn, reinforce existing community inequities.