---
title: "Blog Post 2/3: Data Equity"
subtitle: ""
author: "Group 1"
date: "2024-10-28"
date-modified: "2024-10-28"
draft: false
---

Think about how the principles for advancing equitable data practice are relevant to your data.For two or three of principles, write about how they are relevant and what adhering to the practice would entail for your data.Think about what might be some limitations of your analysis and the potential for abuse or misuse of the data.

We can utilize the principles for advancing equitable data practices by applying the principles of beneficence, respect for persons, and justice to the exploration of our data set. 

These principles are relevant for a few reasons. First, looking at beneficence, we may consider how the findings in our data set are being used by local or federal governments, as well as how we are using the data. We can see from this principle what the best actions for the county to take in response to traffic violations would be. Additionally adhering to this practice for our group's project may look like researching into how the government is using this dataset. 

Furthermore, we can look at the principle of justice. This is relevant to our data as we can see the members of this sample that are facing violations or get into accidents. We can see if they are more at risk than others, and provide some insight through our findings to see if there is any injustice within this county of Maryland response, whether through law or bill. 

Some limitations of our analysis could be missing data, data not provided or included as a variable, and lack of information on the internet to see the local or federal governments lack of/ or response to this data. Some misuse of the data could be government surveillance in high at-risk areas or strict law enforcement. It could also look like policy changes without community input and in turn renforce community inequities. 




